/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiResolveRouteImport } from './routes/api/resolve'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as RoomCodeRouteImport } from './routes/room/$code'
import { Route as ApiDriveIdRouteImport } from './routes/api/drive/$id'
import { Route as ApiMediaIdRouteImport } from './routes/api/media.$id'
import { Route as ApiRoomsIndexRouteImport } from './routes/api/rooms/index'
import { Route as ApiRoomsSplatRouteImport } from './routes/api/rooms/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResolveRoute = ApiResolveRouteImport.update({
  id: '/api/resolve',
  path: '/api/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveIdRoute = ApiDriveIdRouteImport.update({
  id: '/api/drive/$id',
  path: '/api/drive/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsIndexRoute = ApiRoomsIndexRouteImport.update({
  id: '/api/rooms/',
  path: '/api/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsSplatRoute = ApiRoomsSplatRouteImport.update({
  id: '/api/rooms/$',
  path: '/api/rooms/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/upload': typeof ApiUploadRoute
  '/room/$code': typeof RoomCodeRoute
  '/api/drive/$id': typeof ApiDriveIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/rooms/$': typeof ApiRoomsSplatRoute
  '/api/rooms/': typeof ApiRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/upload': typeof ApiUploadRoute
  '/room/$code': typeof RoomCodeRoute
  '/api/drive/$id': typeof ApiDriveIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/rooms/$': typeof ApiRoomsSplatRoute
  '/api/rooms': typeof ApiRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/upload': typeof ApiUploadRoute
  '/room/$code': typeof RoomCodeRoute
  '/api/drive/$id': typeof ApiDriveIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/rooms/$': typeof ApiRoomsSplatRoute
  '/api/rooms/': typeof ApiRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/resolve'
    | '/api/upload'
    | '/room/$code'
    | '/api/drive/$id'
    | '/api/media/$id'
    | '/api/rooms/$'
    | '/api/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/resolve'
    | '/api/upload'
    | '/room/$code'
    | '/api/drive/$id'
    | '/api/media/$id'
    | '/api/rooms/$'
    | '/api/rooms'
  id:
    | '__root__'
    | '/'
    | '/api/resolve'
    | '/api/upload'
    | '/room/$code'
    | '/api/drive/$id'
    | '/api/media/$id'
    | '/api/rooms/$'
    | '/api/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiResolveRoute: typeof ApiResolveRoute
  ApiUploadRoute: typeof ApiUploadRoute
  RoomCodeRoute: typeof RoomCodeRoute
  ApiDriveIdRoute: typeof ApiDriveIdRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ApiRoomsSplatRoute: typeof ApiRoomsSplatRoute
  ApiRoomsIndexRoute: typeof ApiRoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resolve': {
      id: '/api/resolve'
      path: '/api/resolve'
      fullPath: '/api/resolve'
      preLoaderRoute: typeof ApiResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/$id': {
      id: '/api/drive/$id'
      path: '/api/drive/$id'
      fullPath: '/api/drive/$id'
      preLoaderRoute: typeof ApiDriveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/': {
      id: '/api/rooms/'
      path: '/api/rooms'
      fullPath: '/api/rooms/'
      preLoaderRoute: typeof ApiRoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$': {
      id: '/api/rooms/$'
      path: '/api/rooms/$'
      fullPath: '/api/rooms/$'
      preLoaderRoute: typeof ApiRoomsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiResolveRoute: ApiResolveRoute,
  ApiUploadRoute: ApiUploadRoute,
  RoomCodeRoute: RoomCodeRoute,
  ApiDriveIdRoute: ApiDriveIdRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
  ApiRoomsSplatRoute: ApiRoomsSplatRoute,
  ApiRoomsIndexRoute: ApiRoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
